name: Hello World
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  Hello-World-Job:
    runs-on: codebuild-github-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"
      - run: cat /etc/*release*
